"""Add station scoped tracks

Revision ID: 2d350f63a154
Revises: a166ec8c40ab
Create Date: 2026-09-14 15:30:46.960303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d350f63a154'
down_revision = 'a166ec8c40ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=False),
    sa.Column('album', sa.String(length=200), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=50), nullable=False),
    sa.Column('media_type', sa.String(length=12), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('bitrate_kbps', sa.Integer(), nullable=True),
    sa.Column('sample_rate_hz', sa.Integer(), nullable=False),
    sa.Column('channels', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ingest_status', sa.String(length=12), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("ingest_status IN ('accepted','rejected')", name='ck_tracks_ingest_status'),
    sa.CheckConstraint('duration_ms > 0', name='ck_tracks_duration'),
    sa.CheckConstraint('file_size_bytes > 0', name='ck_tracks_size'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'checksum_sha256', name='uq_tracks_station_checksum')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_station_id'), ['station_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tracks_uuid'), ['uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_uuid'))
        batch_op.drop_index(batch_op.f('ix_tracks_station_id'))

    op.drop_table('tracks')
    # ### end Alembic commands ###
