"""Track Liquidsoap request identity for reconciliation

Revision ID: 9d53a42c7cbb
Revises: dc81ffee4ee2
Create Date: 2026-09-14 17:23:29.179798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d53a42c7cbb'
down_revision = 'dc81ffee4ee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liquidsoap_request_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('socket_identity', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection_decisions', schema=None) as batch_op:
        batch_op.drop_column('socket_identity')
        batch_op.drop_column('liquidsoap_request_id')

    # ### end Alembic commands ###
