"""add traffic scheduling and reconciliation

Revision ID: d65fdad18060
Revises: c91d2e3f4a56
Create Date: 2026-09-15 02:16:39.183243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd65fdad18060'
down_revision = 'c91d2e3f4a56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertisers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('external_reference', sa.String(length=80), nullable=True),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=254), nullable=True),
    sa.Column('contact_phone', sa.String(length=40), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'slug', name='uq_advertiser_station_slug')
    )
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_advertisers_station_id'), ['station_id'], unique=False)

    op.create_table('traffic_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','GENERATED','FINALIZED','RECONCILED')", name='ck_traffic_log_status'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'log_date', name='uq_traffic_log_date')
    )
    with op.batch_alter_table('traffic_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_logs_station_id'), ['station_id'], unique=False)

    op.create_table('traffic_stopsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('weekdays', sa.String(length=20), nullable=False),
    sa.Column('local_time', sa.Time(), nullable=False),
    sa.Column('capacity_seconds', sa.Integer(), nullable=False),
    sa.Column('max_spots', sa.Integer(), nullable=True),
    sa.Column('timing_mode', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("timing_mode IN ('SOFT','HARD','NON_INTERRUPTING')", name='ck_traffic_stopset_mode'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'slug', name='uq_traffic_stopset_station_slug')
    )
    with op.batch_alter_table('traffic_stopsets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_stopsets_station_id'), ['station_id'], unique=False)

    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('advertiser_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('target_spot_count', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('DRAFT','ACTIVE','PAUSED','COMPLETED','CANCELLED')", name='ck_campaign_status'),
    sa.CheckConstraint('start_date <= end_date', name='ck_campaign_dates'),
    sa.ForeignKeyConstraint(['advertiser_id'], ['advertisers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'slug', name='uq_campaign_station_slug')
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaigns_station_id'), ['station_id'], unique=False)

    op.create_table('traffic_stopset_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traffic_stopset_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('imaging_asset_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("(item_type='FIXED_IMAGING' AND imaging_asset_id IS NOT NULL) OR (item_type='COMMERCIAL_SLOT' AND imaging_asset_id IS NULL)", name='ck_stopset_item_target'),
    sa.ForeignKeyConstraint(['imaging_asset_id'], ['imaging_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['traffic_stopset_id'], ['traffic_stopsets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traffic_stopset_id', 'position', name='uq_stopset_item_position')
    )
    op.create_table('campaign_schedule_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('weekdays', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('target_spots_per_day', sa.Integer(), nullable=False),
    sa.Column('minimum_separation_seconds', sa.Integer(), nullable=False),
    sa.Column('maximum_spots_per_day', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint('start_time < end_time', name='ck_rule_daypart'),
    sa.CheckConstraint('target_spots_per_day > 0', name='ck_rule_target_positive'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('campaign_schedule_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_campaign_schedule_rules_station_id'), ['station_id'], unique=False)

    op.create_table('commercial_creatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('imaging_asset_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('creative_code', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['imaging_asset_id'], ['imaging_assets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'creative_code', name='uq_creative_station_code')
    )
    with op.batch_alter_table('commercial_creatives', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_commercial_creatives_station_id'), ['station_id'], unique=False)

    op.create_table('traffic_placements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('traffic_log_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('traffic_stopset_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_for_utc', sa.DateTime(timezone=True), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('commercial_creative_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('is_makegood', sa.Boolean(), nullable=False),
    sa.Column('makegood_for_id', sa.Integer(), nullable=True),
    sa.Column('event_block_execution_id', sa.Integer(), nullable=True),
    sa.Column('event_block_item_id', sa.Integer(), nullable=True),
    sa.Column('event_block_item_execution_id', sa.Integer(), nullable=True),
    sa.Column('confirmed_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=80), nullable=True),
    sa.Column('advertiser_name', sa.String(length=120), nullable=False),
    sa.Column('campaign_name', sa.String(length=120), nullable=False),
    sa.Column('creative_name', sa.String(length=120), nullable=False),
    sa.Column('creative_code', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('PLANNED','MATERIALIZED','QUEUED','AIRED','MISSED','FAILED','CANCELLED')", name='ck_traffic_placement_status'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['commercial_creative_id'], ['commercial_creatives.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['event_block_execution_id'], ['event_block_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_block_item_execution_id'], ['event_block_item_executions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_block_item_id'], ['event_block_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['makegood_for_id'], ['traffic_placements.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traffic_log_id'], ['traffic_logs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['traffic_stopset_id'], ['traffic_stopsets.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('traffic_log_id', 'traffic_stopset_id', 'position', name='uq_traffic_placement_position')
    )
    with op.batch_alter_table('traffic_placements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_traffic_placements_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('traffic_placements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_placements_station_id'))

    op.drop_table('traffic_placements')
    with op.batch_alter_table('commercial_creatives', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commercial_creatives_station_id'))

    op.drop_table('commercial_creatives')
    with op.batch_alter_table('campaign_schedule_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaign_schedule_rules_station_id'))

    op.drop_table('campaign_schedule_rules')
    op.drop_table('traffic_stopset_items')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_campaigns_station_id'))

    op.drop_table('campaigns')
    with op.batch_alter_table('traffic_stopsets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_stopsets_station_id'))

    op.drop_table('traffic_stopsets')
    with op.batch_alter_table('traffic_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_logs_station_id'))

    op.drop_table('traffic_logs')
    with op.batch_alter_table('advertisers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_advertisers_station_id'))

    op.drop_table('advertisers')
    # ### end Alembic commands ###
