"""Add categories rotations and automation history

Revision ID: dc81ffee4ee2
Revises: 2d350f63a154
Create Date: 2026-09-14 17:12:54.739716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc81ffee4ee2'
down_revision = '2d350f63a154'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_heartbeat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'slug', name='uq_category_station_slug')
    )
    with op.batch_alter_table('media_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_categories_station_id'), ['station_id'], unique=False)

    op.create_table('rotations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'slug', name='uq_rotation_station_slug')
    )
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rotations_station_id'), ['station_id'], unique=False)

    op.create_table('automation_states',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('active_rotation_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('next_slot_index', sa.Integer(), nullable=False),
    sa.Column('track_separation_seconds', sa.Integer(), nullable=False),
    sa.Column('artist_separation_seconds', sa.Integer(), nullable=False),
    sa.Column('worker_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_queue_depth', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['active_rotation_id'], ['rotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('rotation_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rotation_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['media_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rotation_id'], ['rotations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rotation_id', 'position', name='uq_rotation_slot_position')
    )
    with op.batch_alter_table('rotation_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rotation_slots_rotation_id'), ['rotation_id'], unique=False)

    op.create_table('track_categories',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['media_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'category_id')
    )
    op.create_table('selection_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('rotation_id', sa.Integer(), nullable=True),
    sa.Column('slot_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('selected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('relaxation', sa.String(length=24), nullable=False),
    sa.Column('reason', sa.String(length=120), nullable=False),
    sa.CheckConstraint("status IN ('selected','queued','started','failed')", name='ck_decision_status'),
    sa.ForeignKeyConstraint(['category_id'], ['media_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rotation_id'], ['rotations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['slot_id'], ['rotation_slots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('selection_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_selection_decisions_station_id'), ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('selection_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_selection_decisions_station_id'))

    op.drop_table('selection_decisions')
    op.drop_table('track_categories')
    with op.batch_alter_table('rotation_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rotation_slots_rotation_id'))

    op.drop_table('rotation_slots')
    op.drop_table('automation_states')
    with op.batch_alter_table('rotations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rotations_station_id'))

    op.drop_table('rotations')
    with op.batch_alter_table('media_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_categories_station_id'))

    op.drop_table('media_categories')
    op.drop_table('automation_heartbeat')
    # ### end Alembic commands ###
