"""Add clocks and weekly schedule

Revision ID: f2d3b66ece57
Revises: 9d53a42c7cbb
Create Date: 2026-09-14 18:06:38.345430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d3b66ece57'
down_revision = '9d53a42c7cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'slug', name='uq_clock_station_slug')
    )
    with op.batch_alter_table('clocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clocks_station_id'), ['station_id'], unique=False)

    op.create_table('clock_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clock_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('slot_type', sa.String(length=12), nullable=False),
    sa.Column('rotation_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.CheckConstraint("(slot_type = 'ROTATION' AND rotation_id IS NOT NULL AND category_id IS NULL) OR (slot_type = 'CATEGORY' AND category_id IS NOT NULL AND rotation_id IS NULL)", name='ck_clock_slot_target'),
    sa.CheckConstraint('position > 0', name='ck_clock_slot_position'),
    sa.ForeignKeyConstraint(['category_id'], ['media_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['clock_id'], ['clocks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rotation_id'], ['rotations.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clock_id', 'position', name='uq_clock_slot_position')
    )
    with op.batch_alter_table('clock_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clock_slots_clock_id'), ['clock_id'], unique=False)

    op.create_table('clock_states',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('clock_id', sa.Integer(), nullable=True),
    sa.Column('occurrence_key', sa.String(length=120), nullable=True),
    sa.Column('next_slot_index', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['clock_id'], ['clocks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('station_id')
    )
    op.create_table('rotation_cursors',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('station_id', sa.Integer(), sa.ForeignKey('stations.id', ondelete='CASCADE'), nullable=False),
    sa.Column('rotation_id', sa.Integer(), sa.ForeignKey('rotations.id', ondelete='CASCADE'), nullable=False),
    sa.Column('next_slot_index', sa.Integer(), nullable=False),
    sa.UniqueConstraint('station_id', 'rotation_id', name='uq_rotation_cursor_station_rotation')
    )
    op.create_table('schedule_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('clock_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name='ck_schedule_weekday'),
    sa.ForeignKeyConstraint(['clock_id'], ['clocks.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'weekday', 'start_time', name='uq_schedule_station_day_time')
    )
    with op.batch_alter_table('schedule_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_assignments_station_id'), ['station_id'], unique=False)

    with op.batch_alter_table('automation_states', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_clock_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_automation_default_clock', 'clocks', ['default_clock_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('selection_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clock_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('clock_slot_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schedule_assignment_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('schedule_occurrence', sa.String(length=120), nullable=True))
        batch_op.create_foreign_key('fk_decision_clock', 'clocks', ['clock_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_decision_assignment', 'schedule_assignments', ['schedule_assignment_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key('fk_decision_clock_slot', 'clock_slots', ['clock_slot_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=64), nullable=False, server_default='UTC'))
        batch_op.alter_column('timezone', server_default=None)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stations', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    with op.batch_alter_table('selection_decisions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_decision_clock_slot', type_='foreignkey')
        batch_op.drop_constraint('fk_decision_assignment', type_='foreignkey')
        batch_op.drop_constraint('fk_decision_clock', type_='foreignkey')
        batch_op.drop_column('schedule_occurrence')
        batch_op.drop_column('schedule_assignment_id')
        batch_op.drop_column('clock_slot_id')
        batch_op.drop_column('clock_id')

    with op.batch_alter_table('automation_states', schema=None) as batch_op:
        batch_op.drop_constraint('fk_automation_default_clock', type_='foreignkey')
        batch_op.drop_column('default_clock_id')

    with op.batch_alter_table('schedule_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_assignments_station_id'))

    op.drop_table('schedule_assignments')
    op.drop_table('rotation_cursors')
    op.drop_table('clock_states')
    with op.batch_alter_table('clock_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clock_slots_clock_id'))

    op.drop_table('clock_slots')
    with op.batch_alter_table('clocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clocks_station_id'))

    op.drop_table('clocks')
    # ### end Alembic commands ###
